  api: 
    build: .
    volumes:
      - ./:/src/
    ports: 
      - "80:4000"
    links: 
      - db:db

  db:
    image: mysql:5.7
    restart: always
    container_name: container-mysql
    environment:
      MYSQL_ROOT_HOST: '&'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'coppel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    ports: 
      - "3307:3306"
    volumes:
      - './data/db:/var/lib/mysql'